theme: jekyll-theme-cayman
title: ownCloud Quickstart Guide
description: This quickstart guide will enable you to install an ownCloud server through either Docker or OpenShift, it walks you through adding new users and connecting to the server through the ownCloud Desktop Client. 